ssh_authorized_keys:
- ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIInP9GAskxelbmEOiLDiYfpDQcXUvvoQEjphI7JEhQ6J
run_cmd:
- "sudo vgchange -ay"
k3os:
  modules:
  - kvm
  - nvme
  - nfs
  dns_nameservers:
  - 192.168.1.86
  - 1.1.1.1
  ntp_servers:
  - 0.uk.pool.ntp.org
  - 1.uk.pool.ntp.org
  - 2.uk.pool.ntp.org
  - 3.uk.pool.ntp.org
  password: "rancher"
  server_url: https://k3os-a:6443
  token: "K10e4891be7be93080260e275314d019af45a03d0029e12dcaec874f816994b7cc9::server:60de3d7ac61f8e41ddae3668186a7c6d"
  # labels:
  #   region: us-west-1
  #   somekey: somevalue
  k3s_args:
  - agent
  # - "--disable-agent"
hostname: k3os-b
write_files:
- enconding: ""
  content: |-
    #!/bin/bash
    write_log () {
        local message="${1}"
        logger -t "run-cmd" "${message}"
        echo "${message}"
    }
    write_log "Getting the service using eth0..."
    ETH0=$(connmanctl services | awk '{ print $3 }' | while read -r s1; do connmanctl services $s1 | grep -q "eth0" && echo "$s1"; done)
    write_log "eth0 is bound to: ${ETH0}"
    write_log "Setting up manual net config..."
    connmanctl config $ETH0 --ipv4 manual 10.20.0.101 255.255.255.0 10.20.0.1 --nameservers 192.168.1.86 1.1.1.1
    connmanctl config $ETH0 --domains our.house
    connmanctl config $ETH0 --timeservers 0.uk.pool.ntp.org 1.uk.pool.ntp.org 2.uk.pool.ntp.org 3.uk.pool.ntp.org
    connmanctl config $ETH0 --ipv6 off
    write_log "Restarting connman..."
    service connman restart
    write_log "$(connmanctl services $ETH0)"
    write_log "Network setup done."
  owner: root:root
  path: /etc/run-cmd.sh
  permissions: '0755'
run_cmd:
- "/etc/run-cmd.sh"
